[package]
name = "dyn-adt-base"
version = "0.1.0"
edition = "2021"

[dependencies]
const-fnv1a-hash = "1.1.0"
entoli = "0.1.2"
inventory = "0.3.15"
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }

